[package]
name = "hx711-spi-ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nb = "1.0.0"
rppal = { version = "0.12.0", features = ["hal"] }
hx711_spi = "0.3.1"
