[package]
name = "hd44780"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hd44780-hal = "0.2.1"
linux-embedded-hal = "0.2"